### ISSUE TITLE
Exception when using with react-native-screens

### ISSUE THREAD

**Issue by evert-smit** [react-navigation/animated-switch#6]
Hi - thanks a lot for creating this!

I'm getting the following exception when using the animated SwitchNavigator together with react-native-screens.

The exception doesn't occur when I remove the useScreens(); call in my app, so there must be something in the combination between animated-switch and react-native-screens that causes this.

```
java.lang.IllegalStateException: ScreenContainer is not attached under ReactRootView
        at com.swmansion.rnscreens.ScreenContainer.findRootFragmentActivity(ScreenContainer.java:95)
        at com.swmansion.rnscreens.ScreenContainer.getOrCreateTransaction(ScreenContainer.java:112)
        at com.swmansion.rnscreens.ScreenContainer.detachScreen(ScreenContainer.java:138)
        at com.swmansion.rnscreens.ScreenContainer.updateIfNeeded(ScreenContainer.java:178)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.java:150)
        at android.view.View.dispatchAttachedToWindow(View.java:18347)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4805)
        at android.view.ViewGroup.addView(ViewGroup.java:4778)
        at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:205)
        at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
        at android.support.transition.ViewGroupOverlayApi18.add(ViewGroupOverlayApi18.java:53)
        at android.support.transition.Visibility.onDisappear(Visibility.java:405)
        at android.support.transition.Visibility.createAnimator(Visibility.java:253)
        at android.support.transition.Transition.createAnimators(Transition.java:744)
        at android.support.transition.TransitionSet.createAnimators(TransitionSet.java:470)
        at android.support.transition.Transition.playTransition(Transition.java:1817)
        at android.support.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:295)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Are the two libraries incompatible? Or is there something to be done to fix/work around this exception?

**Comment by HarishJangra** [comment]
I am also getting this issue.  when using with ```react-navigation-animated-switch```

**Comment by jarvisluong** [comment]
did you follow the installation instruction in `react-native-screens`?

**Comment by evert-smit** [comment]
Installation instructions were followed, MainActivity has been adapted:

```java
public class MainActivity extends ReactFragmentActivity {
```

Package versions:
```json
"react-native-screens": "^1.0.0-alpha.22",
"react-navigation": "^3.9.1",
"react-navigation-animated-switch": "^0.2.0",
```

**Comment by ajanauskas** [comment]
Hey guys I made a project that fully reproduces crash:

https://github.com/ajanauskas/AnimatedSwitchApp/blob/master/App.js

The app works fine in iOS, crashes on Android when navigating. When commenting out `useScreens()`  it doesnt crash Android app anymore.

**Comment by roon83** [comment]
> Ok another finding:
> 
> It seems that `createAnimatedSwitchNavigator` will crash on android when:
> 
> 1. `useScreens()` is used
> 2. Switching away from `StackNavigator`. That is - if `createAnimatedSwitchNavigator` route configs are simple components its all fine.
> 
> Also: Somethings wrong specifically when using `<Transition.Out>`.
> 
> E.g.:
> 
> ```
>   transition: (
>     <Transition.Together>
>       <Transition.Out
>         type="slide-bottom"
>         durationMs={400}
>         interpolation="easeIn"
>       />
>       <Transition.In type="fade" durationMs={500} />
>     </Transition.Together>
>   ),
> ```
> 
> Will cause crash
> 
> ```
>   transition: (
>     <Transition.Together>
>       <Transition.In type="fade" durationMs={500} />
>     </Transition.Together>
>   ),
> ```
> 
> Will not cause crash

I am facing exactly the same problems in my project. It is not working with react-native-screens.

**Comment by AregShahbazian** [comment]
I'm having the exact same issues as @roon83 . I'm currently only running `useScreens()` for IOS, as it crashes for android.

**Comment by jvandenaardweg** [comment]
Facing the same issue here, same problem crashing on Android and not on iOS, same error log like opening post

> Or is there something to be done to fix/work around this exception

Temporary workaround for me:

```javascript
import React from 'react';
import { Platform } from 'react-native';
import { createSwitchNavigator } from 'react-navigation';
import createAnimatedSwitchNavigator from 'react-navigation-animated-switch';

const customCreateSwitchNavigator = Platform.select({
  ios: createAnimatedSwitchNavigator,
  android: createSwitchNavigator
});

// use customCreateSwitchNavigator()
```

**Comment by Hawods** [comment]
Mark. Facing the same issue too, crashing on Android when using useScreens() and createAnimatedSwitchNavigator together.

**Comment by mnzaki** [comment]
Can confirm same exact issue, especially about navigating away from one screen in a nested StackNavigator, to another screen in a different StackNavigator (also nested in same SwitchNavigator)

**Comment by kesha-antonov** [comment]
On the same boat

**Comment by Zloka** [comment]
Same issue here on Android.

**Comment by Unforgiven-wanda** [comment]
Same issue.

**Comment by felippepuhle** [comment]
Same.

**Comment by aniciom** [comment]
Same

**Comment by vikjovanov** [comment]
Still this bug. 
I had to delete all my "createAnimatedSwitchNavigator" and replace them by "createSwitchNavigator"

**Comment by taeingyu** [comment]
seems not fixed yet. any updates?

**Comment by smolster** [comment]
Still an issue!
